image:
  pullPolicy: Always

imagePullSecrets:
  - name: github

replicaCount: 2

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 10
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 120

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 500m
    memory: 2Gi

# livenessProbe:
#   failureThreshold: 3
#   httpGet:
#     path: /
#     port: 3300
#     scheme: HTTP
#   initialDelaySeconds: 60
#   periodSeconds: 40
#   timeoutSeconds: 40
#   successThreshold: 1

# readinessProbe:
#   failureThreshold: 3
#   httpGet:
#     path: /
#     port: 3300
#     scheme: HTTP
#   initialDelaySeconds: 60
#   periodSeconds: 40
#   timeoutSeconds: 40
#   successThreshold: 2

service:
  type: ClusterIP
  port: 3300

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

configMap:
  CANON_API: "https://healthycommunitiesnc.org"
  CANON_LANGUAGE_DEFAULT: "en"
  CANON_LANGUAGES: "en"
  CANON_CMS_ENABLE: "false"
  CANON_CMS_CUBES: "https://api.healthycommunitiesnc.org/tesseract/"
  CANON_CMS_GENERATOR_TIMEOUT: "120000"
  CANON_CMS_REQUESTS_PER_SECOND: "40"
  CANON_CONST_STORAGE_BUCKET: "x"
  CANON_CONST_TESSERACT: "https://api.healthycommunitiesnc.org/tesseract/"
  CANON_GOOGLE_ANALYTICS: "UA-219881506-1"
  WDS_SOCKET_PORT: "0"

secrets:
  CANON_CMS_DB: cG9zdGdyZXNxbDovL3JlYWRvbmx5OkZ5QkE4Q3FoZm52UkpRY280WWlCQDM0LjE3MS4yMDUuMzQ6NTQzMi9oZWFsdGh5LWNvbW11bml0aWVzLWNtcw==
  CANON_AWS_DB: bXlzcWw6Ly9kYXRhd2hlZWw6ZGF0YXdoZWVsX3B3b3JkQGNmYy1wcm9kLmMxZjMybnhweWtvNS51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206MzMwNi9jZmNfY2Rw
  FLICKR_API_KEY: ZDRmMDk1ZmQ2NjhkZTZmZGNlOTE0ZTVjOTY5M2Q1NjM=

ingress:
  enabled: false
