name: "[Google Cloud] Deploy an Image into Cloud Run"

# trigger the workflow manually to deploy the required app
on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Image to Build'
        required: true
        default: 'cfc-site-dev:latest-dev'

# environment variables used on the respective workflow
env:
  # docker variables
  IMAGE_NAME: cfc-site-dev
  IMAGE_TAG: latest-dev
  # canon env variables
  CANON_LANGUAGES: "en"
  CANON_LANGUAGE_DEFAULT: "en"
  CANON_LOGINS: "true"
  # canon-cms env variables
  CANON_CMS_ENABLE: "true"
  CANON_CMS_LOGGING: "true"
  # canon env secrets (using github secrets)
  CANON_API: ${{ secrets.CANON_API }}
  CANON_GOOGLE_ANALYTICS: ${{ secrets.CANON_GOOGLE_ANALYTICS }}
  # canon-cms env secrets (using github secrets)
  CANON_CMS_CUBES: ${{ secrets.CANON_CMS_CUBES }}
  CANON_CMS_DB: ${{ secrets.CANON_CMS_DB }}
  CANON_CONST_TESSERACT: ${{ secrets.CANON_CONST_TESSERACT }}
  CANON_CONST_STORAGE_BUCKET: ${{ secrets.CANON_CONST_STORAGE_BUCKET }}
  FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
  # google cloud secrets (using github secrets)
  GCP_ARTIFACT_REGISTRY_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_REPO_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  # deploys the recently created docker image via google cloud build
  deploy:
    needs: build
    name: Deploy Docker Image to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Image to Cloud Run
        run: |-
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image=us-central1-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/${{env.GCP_ARTIFACT_REGISTRY_REPO_NAME}}/${{ github.event.inputs.build }} \
            --set-env-vars=CANON_CMS_GENERATOR_TIMEOUT=${{ env.CANON_CMS_GENERATOR_TIMEOUT }} \
            --set-env-vars=CANON_CMS_REQUESTS_PER_SECOND=${{ env.CANON_CMS_REQUESTS_PER_SECOND }} \
            --set-env-vars=CANON_LANGUAGES=${{ env.CANON_LANGUAGES }} \
            --set-env-vars=CANON_LANGUAGE_DEFAULT=${{ env.CANON_LANGUAGE_DEFAULT }} \
            --set-env-vars=CANON_CMS_ENABLE=${{ env.CANON_CMS_ENABLE }} \
            --set-env-vars=CANON_CMS_LOGGING=${{ env.CANON_CMS_LOGGING }} \
            --set-env-vars=CANON_API=${{ env.CANON_API }} \
            --set-env-vars=CANON_CMS_CUBES=${{ env.CANON_CMS_CUBES }} \
            --set-env-vars=CANON_CMS_DB=${{ env.CANON_CMS_DB }} \
            --set-env-vars=CANON_CONST_TESSERACT=${{ env.CANON_CONST_TESSERACT }} \
            --set-env-vars=CANON_CONST_STORAGE_BUCKET=${{ env.CANON_CONST_STORAGE_BUCKET }} \
            --set-env-vars=FLICKR_API_KEY=${{ env.FLICKR_API_KEY }} \
            --port=3300 \
            --region=us-central1 \
            --min-instances=0 \
            --max-instances=4 \
            --allow-unauthenticated
